name: EPG Update
on:
  push:
  schedule:
    - cron: "15 16,18,20,22,0,2,4,6,8,10,12,14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update EPG Files
        run: |
          rm -f epg.xml && wget https://epg.112114.xyz/pp.xml -O epg.xml
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          git commit -m "EPG Automatic Update."
      - name: Push Changes
        run: git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
